### PR TITLE
Feature/dts movielens example

### PR DESCRIPTION
**Pull request by dvarelas**

### CODE REVIEW

**Review by pm3310 — APPROVED** [review]
Awesome! Feel free to merge it! The next PR will be the same but using the Independent Bandits with BetaTS and EGreedy in order to compare the results

**Comment by pm3310** [comment]
@dvarelas I ran in the same notebook the IndependentBandit with BetaTS and it's clear the Dirichlet is the big winner :-)

**Comment by pm3310** [comment]
This is for BetaTS
betats

**Comment by pm3310** [comment]
This is for Dirichlet

dirichlet

**Comment by dvarelas** [comment]
> @dvarelas I ran in the same notebook the IndependentBandit with BetaTS and it's clear the Dirichlet is the big winner :-)

@pm3310 Awesome! I cannot merge it I don't have write access :(

**Comment by pm3310** [comment]
@dvarelas admin access granted :-) give it a try again to make sure it works

**Pull request merged**
